### PR TITLE
Ignore UtilityFunction cop in all specs

### PR DESCRIPTION
**Pull request by pyromaniackeca**

### CODE REVIEW

**Comment by pyromaniackeca** [comment]
/reviewme @rainforestapp/devs @grodowski 

I also tried to see why the data_corrections aren't being excluded, but didn't have much luck, I'll probably try again in the future.

**Comment by grodowski** [comment]
@pyromaniackeca I found out today that reek has a bunch of issues open related to this: e.g. https://github.com/troessner/reek/issues/1482

**Comment by grodowski** [comment]
The other aspect of how `pronto-reek` calls `Reek::Examiner` with a file argument might be that in this case the `exclude_paths` are not used at all?https://github.com/troessner/reek/commit/cd460401fbd904a92212cedfb4819d1d839b6fdf

**Review by grodowski — APPROVED** [review]

**Comment by pyromaniackeca** [comment]
@grodowski Thanks for looking into it.

I think you're right that `exclude_paths` are completely ignored. In my attempts to make it work, I opened up the reek gem and set some breakpoints to try and figure out what's going on and I could not figure out where exactly it was checking the `exclude_paths` when run via pronto.

**Comment by pyromaniackeca** [comment]
We've stopped reporting reek issues in PRs entirely, so this is no longer required.

**Pull request closed without merging**
