### PR TITLE
Set max line length to 120

### PR DESCRIPTION
**Pull request by shosti**
@rainforestapp/devs 👍/👎❓

### CODE REVIEW

**Comment by maciejgryka** [comment]
:+1: disable

**Comment by jbarber** [comment]
@maciejgryka Not sure whether you think we should enable it, or disable it :)

I think we should have a limit - IMO long lines are a code smell that you're trying to do too much in an expression.

**Comment by maciejgryka** [comment]
@jbarber right, that was not the clearest comment :P changed

**Comment by usami** [comment]
:+1:

**Pull request merged**
