### PR TITLE
0.11.0

### PR DESCRIPTION
**Pull request by magni-**
Just Rubocop updates: https://github.com/rainforestapp/rf-stylez/compare/v0.10.0...pp/0.11.0

### CODE REVIEW

**Comment by kruszczynski** [comment]
I've added one comment in the rubocop upgrade PR https://github.com/rainforestapp/rf-stylez/pull/111/files#r600331620 - since you're modifying stuff here's it'd be a nice win

**Comment by jbarber** [comment]
@kruszczynski / @magni- is there something blocking this PR?

@kruszczynski is your suggestion to change the gem spec so it's:
```
spec.add_runtime_dependency 'rubocop', '1.12'
```
?

**Comment by kruszczynski** [comment]
@jbarber opened #120

**Review by kruszczynski — APPROVED** [review]

**Pull request merged**
